use_frameworks!

target 'EHFlexibleItemsView_Example' do
  pod 'EHFlexibleItemsView', :path => '../'
  pod 'Masonry', '~> 0.6.4'
  pod 'YYCategories', '~> 1.0.1'

  target 'EHFlexibleItemsView_Tests' do
    inherit! :search_paths

    
  end
end
